"""criacao das tabelas de fatores e gtfs

Revision ID: e038dac880c3
Revises: 
Create Date: 2026-06-06 00:07:54.479626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e038dac880c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accident_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('involved', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accident_rate_mode'), 'accident_rate', ['mode'], unique=True)
    op.create_table('bus_routes',
    sa.Column('route_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route_short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('route_long_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('route_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('bus_stops',
    sa.Column('stop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stop_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stop_lat', sa.Float(), nullable=True),
    sa.Column('stop_lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_table('crime_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('robberies', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crime_rate_mode'), 'crime_rate', ['mode'], unique=True)
    op.create_table('flood_risk_streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rain_multiplier', sa.Float(), nullable=False),
    sa.Column('tide_multiplier', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flood_risk_streets_street_name'), 'flood_risk_streets', ['street_name'], unique=True)
    op.create_table('fuel_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('km_per_liter', sa.Float(), nullable=False),
    sa.Column('fixed_cost_per_km', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_consumption_mode'), 'fuel_consumption', ['mode'], unique=True)
    op.create_table('tide_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tide_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tide_factors_tide_level'), 'tide_factors', ['tide_level'], unique=True)
    op.create_table('transport_speed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_speed_mode'), 'transport_speed', ['mode'], unique=True)
    op.create_table('uber_price_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('km_min', sa.Float(), nullable=False),
    sa.Column('km_max', sa.Float(), nullable=False),
    sa.Column('min_min', sa.Float(), nullable=False),
    sa.Column('min_max', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uber_price_ranges_service'), 'uber_price_ranges', ['service'], unique=True)
    op.create_table('weather_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('factor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_factors_condition'), 'weather_factors', ['condition'], unique=True)
    op.create_table('bus_trips',
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('route_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shape_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('trip_headsign', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['bus_routes.route_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_index(op.f('ix_bus_trips_route_id'), 'bus_trips', ['route_id'], unique=False)
    op.create_table('bus_stop_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('departure_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['bus_stops.stop_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['bus_trips.trip_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_stop_times_stop_id'), 'bus_stop_times', ['stop_id'], unique=False)
    op.create_index(op.f('ix_bus_stop_times_trip_id'), 'bus_stop_times', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bus_stop_times_trip_id'), table_name='bus_stop_times')
    op.drop_index(op.f('ix_bus_stop_times_stop_id'), table_name='bus_stop_times')
    op.drop_table('bus_stop_times')
    op.drop_index(op.f('ix_bus_trips_route_id'), table_name='bus_trips')
    op.drop_table('bus_trips')
    op.drop_index(op.f('ix_weather_factors_condition'), table_name='weather_factors')
    op.drop_table('weather_factors')
    op.drop_index(op.f('ix_uber_price_ranges_service'), table_name='uber_price_ranges')
    op.drop_table('uber_price_ranges')
    op.drop_index(op.f('ix_transport_speed_mode'), table_name='transport_speed')
    op.drop_table('transport_speed')
    op.drop_index(op.f('ix_tide_factors_tide_level'), table_name='tide_factors')
    op.drop_table('tide_factors')
    op.drop_index(op.f('ix_fuel_consumption_mode'), table_name='fuel_consumption')
    op.drop_table('fuel_consumption')
    op.drop_index(op.f('ix_flood_risk_streets_street_name'), table_name='flood_risk_streets')
    op.drop_table('flood_risk_streets')
    op.drop_index(op.f('ix_crime_rate_mode'), table_name='crime_rate')
    op.drop_table('crime_rate')
    op.drop_table('bus_stops')
    op.drop_table('bus_routes')
    op.drop_index(op.f('ix_accident_rate_mode'), table_name='accident_rate')
    op.drop_table('accident_rate')
    # ### end Alembic commands ###
